language:
    - python

python:
    - "3.3"

script:
    - python setup.py --force
    - source ~/.bashrc
    - which trash.py # test PATH updated
    - touch x
    - trash.py x # test utility
    - cd ./python/detail/unittest
    - python archive.py
