language: python
python:
  - "3.3"
script:
    - chmod +x ./setup.py ./trash.py
    - ./setup.py --force
    - source ~/.bashrc
    - which trash.py # test PATH updated
    - touch x
    - trash.py x # test utility
